"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.exportAuditPdf = exportAuditPdf;
const admin = __importStar(require("firebase-admin"));
const https_1 = require("firebase-functions/v2/https");
const pdfkit_1 = __importDefault(require("pdfkit"));
const crypto_1 = __importDefault(require("crypto"));
const authz_1 = require("../authz");
const audit_1 = require("./audit");
function safeStr(v) {
    return (v !== null && v !== void 0 ? v : "").toString().trim();
}
function safeDate(v) {
    const s = safeStr(v);
    if (!s)
        return null;
    const d = new Date(s);
    if (Number.isNaN(d.getTime()))
        return null;
    return d;
}
async function exportAuditPdf(req) {
    var _a, _b, _c, _d, _e;
    if (!req.auth)
        throw new https_1.HttpsError("unauthenticated", "Sign in required.");
    const clinicId = safeStr((_a = req.data) === null || _a === void 0 ? void 0 : _a.clinicId);
    if (!clinicId)
        throw new https_1.HttpsError("invalid-argument", "clinicId required");
    const from = safeDate((_b = req.data) === null || _b === void 0 ? void 0 : _b.from);
    const to = safeDate((_c = req.data) === null || _c === void 0 ? void 0 : _c.to);
    const limit = Math.max(1, Math.min(2000, Number((_e = (_d = req.data) === null || _d === void 0 ? void 0 : _d.limit) !== null && _e !== void 0 ? _e : 500)));
    const db = admin.firestore();
    const uid = req.auth.uid;
    await (0, authz_1.requireActiveMemberWithPerm)(db, clinicId, uid, "audit.read");
    // ─────────────────────────────
    // Load audit events
    // ─────────────────────────────
    let q = db
        .collection("clinics")
        .doc(clinicId)
        .collection("audit")
        .orderBy("createdAt", "desc")
        .limit(limit);
    // Firestore can accept JS Date for Timestamp comparisons
    if (from)
        q = q.where("createdAt", ">=", from);
    if (to)
        q = q.where("createdAt", "<=", to);
    const snap = await q.get();
    const events = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
    // ─────────────────────────────
    // Build PDF
    // ─────────────────────────────
    const doc = new pdfkit_1.default({ margin: 40 });
    const pdfPromise = collectPdfBuffer(doc);
    header(doc, "Audit log export");
    kv(doc, "Clinic ID", clinicId);
    kv(doc, "Generated by", uid);
    kv(doc, "Generated at", new Date().toISOString());
    kv(doc, "Event count", String(events.length));
    doc.moveDown();
    drawTableHeader(doc);
    for (const e of events) {
        drawRow(doc, e);
    }
    doc.end();
    const buffer = await pdfPromise;
    // ─────────────────────────────
    // Hash (compliance)
    // ─────────────────────────────
    const hash = crypto_1.default.createHash("sha256").update(buffer).digest("hex");
    await (0, audit_1.writeAuditEvent)(db, clinicId, {
        type: "audit.exported",
        actorUid: uid,
        metadata: { count: events.length, sha256: hash },
    });
    return {
        ok: true,
        mimeType: "application/pdf",
        base64: buffer.toString("base64"),
        sha256: hash,
    };
}
// ─────────────────────────────
// Helpers
// ─────────────────────────────
function collectPdfBuffer(doc) {
    return new Promise((resolve, reject) => {
        const chunks = [];
        doc.on("data", (c) => chunks.push(Buffer.isBuffer(c) ? c : Buffer.from(c)));
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", reject);
    });
}
function header(doc, title) {
    doc.fontSize(18).text(title);
    doc.moveDown();
}
function kv(doc, k, v) {
    doc.fontSize(10).text(`${k}: ${v}`);
}
function drawTableHeader(doc) {
    doc.moveDown();
    doc.fontSize(11).text("Time | Type | Actor | Metadata");
    doc.moveDown(0.5);
}
function drawRow(doc, e) {
    var _a, _b, _c;
    const t = ((_a = e.createdAt) === null || _a === void 0 ? void 0 : _a.toDate) ? e.createdAt.toDate().toISOString() : "";
    const actor = ((_c = (_b = e.actorDisplayName) !== null && _b !== void 0 ? _b : e.actorUid) !== null && _c !== void 0 ? _c : "").toString();
    const meta = e.metadata ? safeMeta(e.metadata) : "";
    doc.fontSize(9).text(`${t} | ${e.type} | ${actor} | ${meta}`, { width: 520 });
}
function safeMeta(m) {
    try {
        // keep it compact
        const s = JSON.stringify(m);
        return s.length > 500 ? s.slice(0, 500) + "…" : s;
    }
    catch {
        return "";
    }
}
//# sourceMappingURL=exportAuditPdf.js.map