// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa3hYjrg8LhtY-vFU0qsdvoRmxUfw4kyc',
    appId: '1:326894670032:web:faf341da2c8b385a810ed5',
    messagingSenderId: '326894670032',
    projectId: 'kineticdx-v3-dev',
    authDomain: 'kineticdx-v3-dev.firebaseapp.com',
    storageBucket: 'kineticdx-v3-dev.firebasestorage.app',
    measurementId: 'G-SFP4GCVRCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFjFxBEj71ZItN9kOACRkGqhvZ_oJoGks',
    appId: '1:326894670032:android:0b98020569cf65a6810ed5',
    messagingSenderId: '326894670032',
    projectId: 'kineticdx-v3-dev',
    storageBucket: 'kineticdx-v3-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBahCT-_bIYXDI91SoHVVIeiwCkw7duqU8',
    appId: '1:326894670032:ios:770fff4eb1d61df3810ed5',
    messagingSenderId: '326894670032',
    projectId: 'kineticdx-v3-dev',
    storageBucket: 'kineticdx-v3-dev.firebasestorage.app',
    iosBundleId: 'com.example.kineticdxAppV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBahCT-_bIYXDI91SoHVVIeiwCkw7duqU8',
    appId: '1:326894670032:ios:770fff4eb1d61df3810ed5',
    messagingSenderId: '326894670032',
    projectId: 'kineticdx-v3-dev',
    storageBucket: 'kineticdx-v3-dev.firebasestorage.app',
    iosBundleId: 'com.example.kineticdxAppV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa3hYjrg8LhtY-vFU0qsdvoRmxUfw4kyc',
    appId: '1:326894670032:web:d343193dca1cbf53810ed5',
    messagingSenderId: '326894670032',
    projectId: 'kineticdx-v3-dev',
    authDomain: 'kineticdx-v3-dev.firebaseapp.com',
    storageBucket: 'kineticdx-v3-dev.firebasestorage.app',
    measurementId: 'G-YM77V42HPZ',
  );

}