// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYHrxok4a_iqMBvBPJYoylv3PDw9tjpCk',
    appId: '1:285801770484:web:e90a451092e4a7dc9a9da1',
    messagingSenderId: '285801770484',
    projectId: 'kineticdx-app-v3',
    authDomain: 'kineticdx-app-v3.firebaseapp.com',
    storageBucket: 'kineticdx-app-v3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJhHWeQytzEyYHQg_gkAY8wtBbiG-BpM',
    appId: '1:285801770484:android:6dc71410e04655909a9da1',
    messagingSenderId: '285801770484',
    projectId: 'kineticdx-app-v3',
    storageBucket: 'kineticdx-app-v3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsbTSJ3Ej4tteebF38v2owKIK6fjvLBaw',
    appId: '1:285801770484:ios:c22685abafcca35c9a9da1',
    messagingSenderId: '285801770484',
    projectId: 'kineticdx-app-v3',
    storageBucket: 'kineticdx-app-v3.firebasestorage.app',
    iosBundleId: 'com.example.kineticdxAppV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsbTSJ3Ej4tteebF38v2owKIK6fjvLBaw',
    appId: '1:285801770484:ios:c22685abafcca35c9a9da1',
    messagingSenderId: '285801770484',
    projectId: 'kineticdx-app-v3',
    storageBucket: 'kineticdx-app-v3.firebasestorage.app',
    iosBundleId: 'com.example.kineticdxAppV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYHrxok4a_iqMBvBPJYoylv3PDw9tjpCk',
    appId: '1:285801770484:web:f0d726c91f5cc5df9a9da1',
    messagingSenderId: '285801770484',
    projectId: 'kineticdx-app-v3',
    authDomain: 'kineticdx-app-v3.firebaseapp.com',
    storageBucket: 'kineticdx-app-v3.firebasestorage.app',
  );

}