# Delete all Firebase Cloud Functions in europe-west3 so they can be redeployed cleanly.
# Run from repo root: .\functions\scripts\delete-all-functions.ps1
# Or from functions dir: npm run delete-all-functions
# Then: firebase deploy --only functions

$repoRoot = if ($PSScriptRoot) { (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) } else { (Get-Location).Path }
Set-Location $repoRoot

$region = "europe-west3"
$force = "--force"

$functions = @(
  "getSchemaVersionsFn",
  "clinicCreateFn",
  "updateMemberProfileFn",
  "inviteMemberFn",
  "acceptInviteFn",
  "settingsUpdateClinicProfile",
  "updateClinicProfileFn",
  "settingsUpsertLocation",
  "settingsSetLocationActive",
  "settingsUpsertAppointmentType",
  "settingsSetAppointmentTypeActive",
  "settingsUpdateCalendarDisplayConfig",
  "settingsGetCalendarDisplayConfig",
  "settingsGetClinicProfile",
  "settingsGetMembership",
  "settingsGetClosures",
  "settingsListMembers",
  "settingsListLocations",
  "settingsListAppointmentTypes",
  "settingsGetPublicBookingConfig",
  "settingsGetCommunicationSettings",
  "settingsUpdatePublicBookingConfig",
  "settingsUpdateOnlineBookingEnablement",
  "rebuildPublicBookingMirrorFn",
  "settingsUpdateCommunicationSettings",
  "settingsUpsertPractitionerAvailability",
  "settingsDeletePractitionerAvailability",
  "settingsUpsertPractitionerOverride",
  "settingsDeletePractitionerOverride",
  "setMembershipStatusFn",
  "updateMemberFn",
  "syncMyDisplayNameFn",
  "updateClinicWeeklyHoursFn",
  "upsertStaffProfileFn",
  "setStaffAvailabilityDefaultFn",
  "createClosureFn",
  "deleteClosureFn",
  "createAppointmentFn",
  "createAppointmentSeriesFn",
  "deleteAppointmentFn",
  "updateAppointmentFn",
  "updateAppointmentOccurrenceFn",
  "updateAppointmentSeriesFn",
  "splitAppointmentSeriesFn",
  "updateAppointmentStatusFn",
  "cancelAppointmentFn",
  "createPatientFn",
  "updatePatientFn",
  "mergePatientsFn",
  "deletePatientFn",
  "listPatientsForBookingFn",
  "createEpisodeFn",
  "updateEpisodeFn",
  "closeEpisodeFn",
  "createClinicalNoteFn",
  "amendClinicalNoteFn",
  "finalizeSoapNoteFn",
  "unfinalizeSoapNoteFn",
  "upsertClinicalTestFn",
  "deleteClinicalTestFn",
  "upsertOutcomeMeasureFn",
  "deleteOutcomeMeasureFn",
  "submitAssessmentFn",
  "getAssessmentPackFn",
  "generateAssessmentPdfFn",
  "billingCreateChargeFn",
  "billingCreateInvoiceDraftFn",
  "billingIssueInvoiceFn",
  "billingRecordManualPaymentFn",
  "billingIssueCreditNoteFn",
  "billingUpdateSettingsFn",
  "billingCreateStripePaymentIntentFn",
  "billingGenerateInvoicePdfFn",
  "billingGetInvoicePdfDownloadUrlFn",
  "billingStripeWebhookFn",
  "submitIntakeSessionFn",
  "createGeneralQuestionnaireLinkFn",
  "resolveIntakeLinkTokenFn",
  "exportClosureOverrideAuditReportFn",
  "onBookingRequestCreateV2",
  "onPublicBookingSettingsWrite",
  "onPractitionerWritten",
  "onPublicBookingConfigMirror",
  "onPublicBookingSettingsWriteProjection",
  "projectionsRebuildPublicBookingConfig",
  "onAppointmentWrite_toBusyBlock",
  "mirrorPractitionerToPublic",
  "onClinicalNoteWrite",
  "onSoapNoteWrite",
  "listPublicSlotsFn",
  "getPublicMonthAvailabilityFn",
  "getPublicBookingPractitionersFn",
  "getPublicBookingLocationsFn",
  "getPublicBookingAppointmentTypesFn",
  "getPublicBookingDiagnosticsFn",
  "getManageContextFn",
  "cancelBookingWithTokenFn",
  "rescheduleBookingWithTokenFn",
  "testCallable",
  "onClinicCreatedProvisionDefaults",
  "backfillNotificationsSettings",
  "backfillRoles",
  "backfillMemberPermissions",
  "consumeIntakeInviteFn",
  "bootstrapPublicBookingSettingsFn",
  "createBookingRequestFn",
  "intakePdfOnSubmit",
  "resolveIntakeSessionFromBookingRequestFn",
  "onClinicCreatedProvisionOwnerMembership"
)

$count = 0
foreach ($fn in $functions) {
  Write-Host "Deleting $fn ..."
  firebase functions:delete $fn --region $region $force 2>&1
  if ($LASTEXITCODE -eq 0) { $count++ }
}
Write-Host "Done. Deleted (or already missing): $count. Run: firebase deploy --only functions"
